### ISSUE TITLE
Symfony HTTP instead of string operations

### ISSUE THREAD

**Issue by szepeviktor** [decodelabs/sanctum#1]
You could use Symfony for HTTP header operations.
https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/HttpFoundation/AcceptHeader.php
I think it is already a dependency.

**Comment by betterthanclay** [comment]
Hi Viktor.

Symfony is only a dev dependency through one of the testing packages and not in the production require list - it's not something I'm looking to be dependent on for DecodeLabs packages unless specifically providing compatibility.

A future release of Sanctum will however provide HTTP header propagation via PSR-7 messages (via a future DecodeLabs HTTP package). For now, exporting the headers as strings is enough to make use of the library. Thanks for the suggestion though.
